### ISSUE TITLE
Error 404 NOT FOUND

### ISSUE THREAD

**Issue by Lokotito** [nemec/JDHttpAPI#2]
Hi, runing Jdownloader2 in a headless Debian 9 server, with any error.
I follow the instructions from 1 to 3, but I don't have the file named "opt/update/versioninfo/JD/extensions.installed.json"

Well after that JDHttpAPI shows in SETTINGS->EXTENSION->HttpAPIExtension column, and I can enable and set password. Also I enabled this plugin.
When I try to browse from FireFox (external machine in same subnet) the address http://localadress:8297, the browser shows NOT FOUND:

> HTTP ERROR 404
> 
> Problem accessing /. Reason:
> 
>     Not Found

Logs don't show an error.
I don't know if I can browse this plugin via firefox/crhome directly.

Tnks for any advance.

**Comment by nemec** [comment]
If you can set the password, that's good news.

Based on the error message it sounds like you are trying to access the root page, `http://localhost:8297/`. A 404 is expected there, because there is no root page. Can you try the url with the right path: `http://localhost:8297/addLink`

**Comment by Lokotito** [comment]
Yes I try to browse directly from Firefox browser.
Same not found page, http://192.168.1.100:8297/addLink

> HTTP ERROR 404
> 
> Problem accessing /addLink. Reason:
> 
>     Not Found
I don't know if is relevant but I already have an apache2 serverver runing in same address but 80 port.

**Comment by nemec** [comment]
Since Apache is on a different port you should be fine. What url are you trying to add? Did you format the request correctly with the url in a query parameter, as noted in the Readme?

**Comment by nemec** [comment]
Since Apache is on a different port you should be fine. What url are you trying to add? Did you format the request correctly with the url in a query parameter, as noted in the Readme?

**Comment by Lokotito** [comment]
I test mega link, in address field, inside firefox 59.02:
http://192.168.1.100:8297/addLink?url=https://mega.nz/#LINK

but the page didn't show a passwrod request, and also the page 404 error is showed.
Also tested the mega link and is online.

**Comment by nemec** [comment]
Hmm, that looks correct to me - even without the password it should have given you a different error than 404.

Can you ssh into the debian server and run the following, just to rule out localhost issues?

    curl -v -u ':mypassword' 'http://localhost:8297/addLink?url=https://mega.nz/#LINK'

**Comment by Lokotito** [comment]
Login into server using ssh:

> curl -v -u ':MyPass' 'http://192.168.1.100:8297/addLink?url=https://mega.nz/#MyLink'

this is the output:
```
*   Trying 192.168.1.100...
* TCP_NODELAY set
* Connected to 192.168.1.100 (192.168.1.100) port 8297 (#0)
* Server auth using Basic with user ''
> GET /addLink?url=https://mega.nz/ HTTP/1.1
> Host: 192.168.1.100:8297
> Authorization: Basic Om8wZVRjMG8=
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Thu, 29 Mar 2018 15:46:59 GMT
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 323
< Server: Jetty(9.4.7.v20170914)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /addLink. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.7.v20170914</a><hr/>

</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host 192.168.1.100 left intact
```

Same 404 error.

**Comment by nemec** [comment]
Please try it with `localhost`, rather than `192.168.1.100` - there is a small but subtle difference between the two when you're running directly from the server.

**Comment by Lokotito** [comment]
Same error with local host:

> curl -v -u ':MyPass' 'http://localhost:8297/addLink?url=https://mega.nz/#MyLink'

```
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8297 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8297 (#0)
* Server auth using Basic with user ''
> GET /addLink?url=https://mega.nz/ HTTP/1.1
> Host: localhost:8297
> Authorization: Basic Om8wZVRjMG8=
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Thu, 29 Mar 2018 15:51:51 GMT
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 323
< Server: Jetty(9.4.7.v20170914)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /addLink. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.7.v20170914</a><hr/>

</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by nemec** [comment]
OH there is one thing I forgot to ask: in the plugin settings, did you check the 'Allow GET' option?

**Comment by Lokotito** [comment]
Accessing via my.jdownloader.org, enabled all this:

```
HttpAPIExtension = ENABLED
HttpAPI: Password = MyPass
HttpAPI: Port = 8297
HttpAPI: Use Password = enabled
HttpAPI: Allow Get = enabled
```
also try whit a simple http JPG image, but same error shows.

**Comment by nemec** [comment]
Hmm, that's really strange. Assuming those settings have 'synced' with JD everything you're doing looks right. I'm not sure what the issue might be.

You can try the following too, just for completeness, but I'm not sure if it will work:

    curl -v -u ':MyPass' -X POST 'http://localhost:8297/addLink' -d '{"url":"https://mega.nz/#MyLink"}'

**Comment by Lokotito** [comment]
A connection refused error shows:

```
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8297 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8297 (#0)
* Server auth using Basic with user ''
> POST /addLink HTTP/1.1
> Host: localhost:8297
> Authorization: Basic Om8wZVRjMG8=
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Length: 80
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 80 out of 80 bytes
< HTTP/1.1 200 OK
< Date: Thu, 29 Mar 2018 16:15:16 GMT
< Content-Type: application/json;charset=utf-8
< Content-Length: 17
< Server: Jetty(9.4.7.v20170914)
<
{"success":true}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by Lokotito** [comment]
My bad, at the end of log shows SUCCESS: TRUE, and checking in LINKCOLLECTOR shows the mega link.

Also tested only with this command:

> curl -v -u ':MyPass' 'http://localhost:8297/addLink' -d '{"url":"https://mega.nz/#MyLink"}'

and

> curl -v -u ':MyPass' 'http://192.168.1.100:8297/addLink' -d '{"url":"https://mega.nz/#MyLink"}'

Is there a way to use HTTPS instead of http ?? like: HTTPS://localhost:8297/addLink
Also, using php POST method inside a http page, will send the address in the same way, right?

Thank you for your time and advises.

**Comment by nemec** [comment]
> Is there a way to use HTTPS instead of http ??

That is something you would have to set up yourself, using apache or nginx. You would have to have a domain name to get a trusted certificate or use something self-signed, both of which are kind of out of scope of the plugin.

> Also, using php POST method inside an http page, will send the address in the same way, right?

Yes it will. It might be easier to set up HTTPS within php. If you call php with HTTPS and php is calling `http://localhost`, it doesn't matter that localhost is over http because it never hits the network.

**Comment by Lokotito** [comment]
Thank you, I really prefer access JD in local network, because my.jdownloader.org is a little SLOW, and I really don't know if they "Store" my data and what they do whit that.

Hoppe you will continue with the development of this plugin.

Best regards.

**Comment by nemec** [comment]
I agree completely, that's also the primary reason why I wrote this plugin :)

Who knows what data they're storing.
